[package]
name = "rpn_calc_JM"
version = "0.1.0"
authors = ["JM268"]
description = "RPN(Reverse Polish Notatio) library"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
